172.31.16.154
[web]
172.31.5.161

[web:vars]
DB_URL="http://db.bnsaws.online"

[localhost]
localhost

[localhost:vars]
#Course="DevOps with AWS"
#Trainer="nasa"
#Duration="120hrs"
#WISHES="Morning from inventory"

[db]
172.31.5.162

[app]
172.31.5.163

[all:children]
web
db
app